import { VideoSamplePreset } from '../types';

export const SAMPLE_PRESETS: VideoSamplePreset[] = [
  {
    id: 'sample-tech-dialogue',
    title: 'AI Studio Keynote (Dual Speaker)',
    description: 'Two distinct speakers discussing cutting-edge neural video dubbing and voice modeling.',
    duration: 15,
    thumbnail: 'https://images.unsplash.com/photo-1576267423445-b2e0074d68a4?w=600&auto=format&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    speakersCount: 2,
    tags: ['Tech', '2 Speakers', 'Male & Female', 'Conversational'],
    speakers: [
      {
        id: 'speaker_1',
        name: 'Speaker 1 (Sarah / রাহেলা)',
        detectedGender: 'female',
        approxAge: 27,
        ageCategory: 'young',
        pitchHz: 210,
        pitchDesc: 'High-clarity soprano (210 Hz)',
        tone: 'Warm, Articulate, Vibrant',
        speakingSpeed: 1.05,
        speakingSpeedWpm: 150,
        emotion: 'Enthusiastic & Engaging',
        accent: 'International English',
        speakingStyle: 'Professional Keynote Speaker',
        voicePreservationEnabled: true,
        targetVoiceMode: 'preserve',
        assignedVoiceName: 'Kore (Young Warm Female)',
        voiceProviderId: 'gemini_kore',
        similarity: 94,
        ageCharacterAdjustment: 'young',
        pitchAdjustment: 'natural',
        speedAdjustment: 1.0,
        emotionOverride: 'preserve',
        avatarBgColor: '#ec4899',
      },
      {
        id: 'speaker_2',
        name: 'Speaker 2 (David / কামাল)',
        detectedGender: 'male',
        approxAge: 48,
        ageCategory: 'mature',
        pitchHz: 115,
        pitchDesc: 'Deep resonant baritone (115 Hz)',
        tone: 'Authoritative, Deep, Measured',
        speakingSpeed: 0.95,
        speakingSpeedWpm: 130,
        emotion: 'Serious & Confident',
        accent: 'Standard Broadcast',
        speakingStyle: 'Executive Presentation',
        voicePreservationEnabled: true,
        targetVoiceMode: 'preserve',
        assignedVoiceName: 'Fenrir (Mature Resonant Male)',
        voiceProviderId: 'gemini_fenrir',
        similarity: 92,
        ageCharacterAdjustment: 'mature',
        pitchAdjustment: 'lower',
        speedAdjustment: 0.9,
        emotionOverride: 'preserve',
        avatarBgColor: '#3b82f6',
      },
    ],
    segments: [
      {
        id: 'seg_1',
        speakerId: 'speaker_1',
        startTime: 0.5,
        endTime: 4.8,
        originalText: 'Welcome everyone! Today we are introducing real-time multi-speaker AI video dubbing.',
        translatedText: 'সবাইকে স্বাগতম! আজ আমরা রিয়েল-টাইম বহু-কণ্ঠস্বর এআই ভিডিও ডাবিং উন্মোচন করছি।',
        detectedEmotion: 'Excited & Welcoming',
        speechFitRatio: 0.97,
        visemes: [
          { time: 0.5, viseme: 'O', intensity: 0.8 },
          { time: 1.2, viseme: 'aa', intensity: 0.9 },
          { time: 2.1, viseme: 'E', intensity: 0.7 },
          { time: 3.4, viseme: 'PP', intensity: 0.85 },
          { time: 4.2, viseme: 'TH', intensity: 0.6 },
        ],
      },
      {
        id: 'seg_2',
        speakerId: 'speaker_2',
        startTime: 5.0,
        endTime: 9.8,
        originalText: 'Notice how each character retains their unique vocal age, pitch, and emotional tone seamlessly.',
        translatedText: 'লক্ষ করুন কীভাবে প্রতিটি চরিত্রের বয়স, কণ্ঠের তীব্রতা এবং অনুভূতির স্পষ্ট রূপ হুবহু সংরক্ষিত রয়েছে।',
        detectedEmotion: 'Confident & Informative',
        speechFitRatio: 0.98,
        visemes: [
          { time: 5.1, viseme: 'nn', intensity: 0.7 },
          { time: 6.2, viseme: 'aa', intensity: 0.95 },
          { time: 7.3, viseme: 'CH', intensity: 0.8 },
          { time: 8.5, viseme: 'O', intensity: 0.85 },
          { time: 9.4, viseme: 'sil', intensity: 0.3 },
        ],
      },
      {
        id: 'seg_3',
        speakerId: 'speaker_1',
        startTime: 10.2,
        endTime: 14.5,
        originalText: 'And best of all, the background music and ambient sounds are preserved without any distortion.',
        translatedText: 'এবং সবচেয়ে আনন্দের বিষয় হলো, মূল ব্যাকগ্রাউন্ড মিউজিক এবং সাউন্ড ইফেক্ট কোনো বিকৃতি ছাড়াই অক্ষুণ্ণ থাকে।',
        detectedEmotion: 'Delighted & Concluding',
        speechFitRatio: 0.96,
        visemes: [
          { time: 10.3, viseme: 'aa', intensity: 0.9 },
          { time: 11.5, viseme: 'PP', intensity: 0.75 },
          { time: 12.8, viseme: 'E', intensity: 0.8 },
          { time: 13.9, viseme: 'O', intensity: 0.7 },
        ],
      },
    ],
  },
  {
    id: 'sample-nature-interview',
    title: 'Documentary Interview (Field Recording)',
    description: 'Documentary sequence demonstrating natural background audio separation and emotion preservation.',
    duration: 12,
    thumbnail: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=600&auto=format&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    speakersCount: 2,
    tags: ['Documentary', 'Field Audio', 'Ambient Music'],
    speakers: [
      {
        id: 'speaker_1',
        name: 'Speaker 1 (Interviewer / তানিয়া)',
        detectedGender: 'female',
        approxAge: 32,
        ageCategory: 'young',
        pitchHz: 195,
        pitchDesc: 'Conversational mezzo-soprano (195 Hz)',
        tone: 'Curious, Empathetic, Clear',
        speakingSpeed: 1.0,
        speakingSpeedWpm: 140,
        emotion: 'Curious & Inquisitive',
        accent: 'British Received Pronunciation',
        speakingStyle: 'Investigative Journalism',
        voicePreservationEnabled: true,
        targetVoiceMode: 'preserve',
        assignedVoiceName: 'Zephyr (Refined Female)',
        voiceProviderId: 'gemini_zephyr',
        similarity: 95,
        ageCharacterAdjustment: 'balanced',
        pitchAdjustment: 'natural',
        speedAdjustment: 1.0,
        emotionOverride: 'preserve',
        avatarBgColor: '#8b5cf6',
      },
      {
        id: 'speaker_2',
        name: 'Speaker 2 (Expert / প্রফেসর মাসুদ)',
        detectedGender: 'male',
        approxAge: 58,
        ageCategory: 'senior',
        pitchHz: 108,
        pitchDesc: 'Low resonant elder baritone (108 Hz)',
        tone: 'Wise, Thoughtful, Gravelly',
        speakingSpeed: 0.88,
        speakingSpeedWpm: 120,
        emotion: 'Thoughtful & Nostalgic',
        accent: 'Regional Accent',
        speakingStyle: 'Storytelling & Reflective',
        voicePreservationEnabled: true,
        targetVoiceMode: 'preserve',
        assignedVoiceName: 'Charon (Senior Resonant Voice)',
        voiceProviderId: 'gemini_charon',
        similarity: 91,
        ageCharacterAdjustment: 'mature',
        pitchAdjustment: 'lower',
        speedAdjustment: 0.9,
        emotionOverride: 'preserve',
        avatarBgColor: '#10b981',
      },
    ],
    segments: [
      {
        id: 'seg_doc_1',
        speakerId: 'speaker_1',
        startTime: 0.6,
        endTime: 4.8,
        originalText: 'Can you describe what it felt like when you first stepped into this untouched ecosystem?',
        translatedText: 'আপনি কি বর্ণনা করতে পারবেন যখন প্রথমবার এই অনাবিষ্কৃত প্রাকৃতিক পরিবেশে প্রবেশ করেছিলেন তখন কেমন অনুভূত হয়েছিল?',
        detectedEmotion: 'Curious',
        speechFitRatio: 0.95,
        visemes: [
          { time: 0.6, viseme: 'kk', intensity: 0.8 },
          { time: 1.8, viseme: 'E', intensity: 0.85 },
          { time: 3.2, viseme: 'aa', intensity: 0.9 },
          { time: 4.3, viseme: 'TH', intensity: 0.6 },
        ],
      },
      {
        id: 'seg_doc_2',
        speakerId: 'speaker_2',
        startTime: 5.2,
        endTime: 11.4,
        originalText: 'It was breathtaking. The silence was only broken by the wind and the river flowing below.',
        translatedText: 'সেটি ছিল সত্যিই চোখ জুড়ানো। কেবল বাতাসের দীর্ঘশ্বাস আর নীচের বয়ে চলা নদীর মিষ্টি ধ্বনি নীরবতা ভাঙছিল।',
        detectedEmotion: 'Wonder & Awe',
        speechFitRatio: 0.98,
        visemes: [
          { time: 5.3, viseme: 'E', intensity: 0.9 },
          { time: 6.8, viseme: 'O', intensity: 0.85 },
          { time: 8.4, viseme: 'PP', intensity: 0.7 },
          { time: 10.1, viseme: 'aa', intensity: 0.8 },
        ],
      },
    ],
  },
];
